### ISSUE TITLE
Germline/somatic classification

### ISSUE THREAD

**Issue by dancooke** [Illumina/Pisces#18]
Hi,

I'm trying to use Pisces to call a tumour-only sample. I'm using the following command:

```shell
$ dotnet Pisces.dll -bam tumour.bam -CallMNVs false -g hs37d5 -gVCF false -i hs37d5.chromosomes.bed -OutFolder pisces -RMxNFilter 5,9,0.35
```

I gather from [this documentation](https://github.com/Illumina/Pisces/wiki/Pisces-Quick-Start-5.2.7) that this should call somatic mutations. However, I appear to be getting both germline and somatic variants and I can't seem to find anything in the Pisces VCF that indicates whether the call is classified germline or somatic. Am I to assume Pisces is calling and classifying all these variants as somatic or am I missing something?

Thanks,
Dan

**Comment by tamsen** [comment]
Hi Dan,

Thank you for your interest.

Yes, you are correct. Pisces in default "somatic" mode will just tell you all the variants it finds. It will not attempt to discriminate between somatic and germline variants.  If you want somatic-only, you can run the same sample in somatic mode (default) and germline mode (-ploidy diploid , see the quick start), and use VennVcf included in this package to do the subtraction. If you have a "normal" sample to run in germline mode, even better.

hope this helps,
Tamsen

**Comment by dancooke** [comment]
Hi Tamsen,

I got an error when I tried this:

```shell
$ dotnet VennVcf.dll \
    -if somatic.vcf.gz,germline.vcf.gz \
    -o venn
...
>>> starting Venn
Fatal error encountered comparing paired sample vcfs; Check 1, position 249240544.  Exception: System.ArgumentException: Chromosome name in input allele 'a' or 'b' .vcf is not supported.  Cannot order variants.
   at Pisces.Domain.Models.Alleles.AlleleCompareByLoci.OrderAlleles(CalledAllele a, CalledAllele b, Boolean mFirst) in D:\TeamCity\buildAgent\work\pisces-5.2.7.47\src\lib\Pisces.Domain\Models\Alleles\AlleleCompareByLoci.cs:line 46
   at VennVcf.VennProcessor.AssembleColocatedList(VcfReader Reader, CalledAllele CurrentVariant, Boolean mFirst, Boolean& BackLogExists, List`1& TheBackLog) in D:\TeamCity\buildAgent\work\pisces-5.2.7.47\src\exe\VennVcf\VennVcf.cs:line 389
   at VennVcf.VennProcessor.DoPairwiseVenn(Boolean mFirst) in D:\TeamCity\buildAgent\work\pisces-5.2.7.47\src\exe\VennVcf\VennVcf.cs:line 171

ERROR: Chromosome name in input allele 'a' or 'b' .vcf is not supported.  Cannot order variants.

Stack trace:
   at Pisces.Domain.Models.Alleles.AlleleCompareByLoci.OrderAlleles(CalledAllele a, CalledAllele b, Boolean mFirst) in D:\TeamCity\buildAgent\work\pisces-5.2.7.47\src\lib\Pisces.Domain\Models\Alleles\AlleleCompareByLoci.cs:line 46
   at VennVcf.VennProcessor.AssembleColocatedList(VcfReader Reader, CalledAllele CurrentVariant, Boolean mFirst, Boolean& BackLogExists, List`1& TheBackLog) in D:\TeamCity\buildAgent\work\pisces-5.2.7.47\src\exe\VennVcf\VennVcf.cs:line 389
   at VennVcf.VennProcessor.DoPairwiseVenn(Boolean mFirst) in D:\TeamCity\buildAgent\work\pisces-5.2.7.47\src\exe\VennVcf\VennVcf.cs:line 171
   at VennVcf.Program.ProgramExecution() in D:\TeamCity\buildAgent\work\pisces-5.2.7.47\src\exe\VennVcf\Program.cs:line 73
   at CommandLine.IO.BaseApplication.Execute() in D:\TeamCity\buildAgent\work\pisces-5.2.7.47\src\lib\CommandLine.IO\BaseApplication.cs:line 98
```

Where `somatic.vcf.gz` was generated using the command in my first message, and `germline.vcf.gz` was after adding `-ploidy diploid`. I looked at the variants at `1:249240544`:

```shell
$ bcftools view -H somatic.vcf.gz 1:249240544
1       249240543       .       AG      A       21      q30     DP=13   GT:GQ:AD:DP:VF:NL:SB    0/1:21:11,2:13:0.154:20:-17.0022
1       249240543       .       AGG     A       22      q30     DP=12   GT:GQ:AD:DP:VF:NL:SB    0/1:22:10,2:12:0.167:20:-10.2732
1       249240544       .       G       T       35      PASS    DP=13   GT:GQ:AD:DP:VF:NL:SB    0/1:35:5,3:13:0.231:20:-17.0109
$ bcftools view -H germline.vcf.gz 1:249240544
1       249240544       .       G       T       35      PASS    DP=13   GT:GQ:AD:DP:VF:NL:SB    0/1:0:5,3:13:0.231:20:-17.0109
```

Am I doing something wrong?

Thanks,
Dan

**Comment by tamsen** [comment]
Oh, rats.  No, you are not doing anything wrong. Its a current limitation of the ordering algorithm. It's just used to "chr1, chr2.." type naming.

I added some words to the Limitations section of https://github.com/Illumina/Pisces/wiki/VennVcf-5.2.7-Design-Document :

This tool was developed for a specific product where the chr listed in the vcf follow the pattern "chr1, chr2... chrM" . The current implementation is unfortunately limited such that if the chr are "1, 2.." or "frog" or "mydecoy.L" etc, the ordering algorithm will complain. A cheap work around is to rename your chr to fit the pattern. We will fix this limitation in future releases.

**Comment by tamsen** [comment]
Something like this will probably get you past the issue, until we push the fix 

cat $vcfFolder/$v | grep -v '#' > $outFolder/$body
sed -i -e 's/^/chr/' $outFolder/$body
cat $outFolder/$header $outFolder/$body > $outFolder/$v

**Comment by tamsen** [comment]
Also, what is the coverage depth like for your somatic sample? DP 13 seems low...?

**Comment by tamsen** [comment]
ok, sounds good!

**Comment by tamsen** [comment]
Hi Dan,

I just read your Octopus preprint.  Congratulations on a lot of work! It sounds like really good stuff.

I have one question/comment regarding the Pisces comparison, and I really want to make sure I did not mislead you earlier about what Pisces can and cannot do. Its absolutely not a classifier.  Specifically, this quote "Octopus is sensitive to allele frequencies between 5 and 30%, in contrast to Pisces, which is only sensitive to frequencies between 10 and 20%" is what got me worried.

I think we had some mis-communication last summer regarding the Pisces use cases that I would like to clarify:

1)	Pisces can be run in germline or somatic mode. In somatic mode, it will by default output all variants with VF >= 1%. This may or may not include germline variants. In germline mode, we set the VF cutoff to 20% and assume that variants with VF 20%-70% are likely het calls and variants with VF > 70% are likely homalts. 
2)	Pisces does not make classifications though! When you run Pisces in germline mode, we assume that your input is a germline sample. If you run a somatic sample through the germline variant calling, all variants with VF > 20% (default) will be outputted, no matter if the variants are somatic or germline. That being said, you can _do it_  but you have to understand the limitations of what you are getting out.

3)	So, for example, if you did the following: you ran one tumor sample through Pisces germline and Pisces somatic. Then suppose you subtracted the germline output from the somatic vcf and classified the remaining variants as somatic. This is not a correct or recommended use case of Pisces. Although you can do it in the sense that it is possible to do and get a resulting vcf which might be interesting for investigation, it is not a classification. If in your analysis, you made the assumption that all your somatic variants have frequencies below 20% (because the default germline VF threshold is 20%). You would have basically removed all calls from the somatic output that had VF > 20%.  You would ended up with the conclusion that pisces is not sensitive to somatic variants > 20%. Which is not true as the output of the germline caller is not a classification of “not somatic”.  It just means variants were detected at the settings conducive for calling germline samples. The expectation is that the germline caller is fed germline samples. I've taken an action to go through the VennVcf documentation to make this more clear.

4)	Again, I want to underscore that Pisces is not a classifier between somatic and germline mutations. If it helps, this is how I would do it if I was forcing the workflow, but you'd be in uncharted territory. 
a.	If you have a matched normal sample for your tumor sample, you should run the normal sample through Pisces germline and subtract the resulting variants from the somatic results
b.	If you do not have a matched normal sample, you can run an unrelated normal cohort through Pisces germline and use this as a proxy. You could e.g. use Coriell samples.

I hope this makes it clearer and I'm sorry if I was not very clear earlier in the documentation or in earlier communications. Feel free to email me directly or at pisces@illumina.com if you want to get through directly to me or the team.

Best
Tamsen
