### ISSUE TITLE
Pisces calling error - v5.2.10.49

### ISSUE THREAD

**Issue by saty89** [Illumina/Pisces#32]
Hi, I am running Pisces somatic work flow (Gemini, Pisces and VQR) using v5.2.10.49. The input to this workflow is bam that went through GATK bqsr step. I did not encounter the following issue through the previous version though. At various chromosomes, I see the following - 

18/03/19 12:50 pm 1  Exception reported:
System.Exception: 16M7014.recal.PairRealigned.bam: Error processing chr '9': Alignment error: Found change in direction without encountering stitched direction ---> System.IO.InvalidDataException: Alignment error: Found change in direction without encountering stitched direction
   at Pisces.Domain.Logic.CandidateVariantFinder.GetSupportDirection(CandidateAllele candidate, Read bamAlignment, Int32 startIndexInRead)
   at Pisces.Domain.Logic.CandidateVariantFinder.Create(AlleleCategory type, String chromosome, Int32 coordinate, String reference, String alternate, Read alignment, Int32 startIndexInRead, Int32 wellAnchoredAnchorSize)
   at Pisces.Domain.Logic.CandidateVariantFinder.ExtractInsertionFromOperation(Read alignment, String refChromosome, Int32 opStartIndexInRead, UInt32 operationLength, Int32 opStartIndexInReference, String chromosomeName)
   at Pisces.Domain.Logic.CandidateVariantFinder.ProcessCigarOps(Read alignment, String refChromosome, Int32 readStartPosition, String chromosomeName)
   at Pisces.Logic.SomaticVariantCaller.Execute()
   at Pisces.Processing.Logic.BaseGenomeProcessor.ProcessByBam(BamWorkRequest workRequest, String chrName)
   --- End of inner exception stack trace ---.
18/03/19 12:50 pm 1  Unloaded chromosome '9', all jobs complete.

18/03/19 1:00 pm 1  Exception reported:
System.Exception: 16M7014.recal.PairRealigned.bam: Error processing chr '19': Alignment error: Found change in direction without encountering stitched direction ---> System.IO.InvalidDataException: Alignment error: Found change in direction without encountering stitched direction
   at Pisces.Domain.Logic.CandidateVariantFinder.GetSupportDirection(CandidateAllele candidate, Read bamAlignment, Int32 startIndexInRead)
   at Pisces.Domain.Logic.CandidateVariantFinder.Create(AlleleCategory type, String chromosome, Int32 coordinate, String reference, String alternate, Read alignment, Int32 startIndexInRead, Int32 wellAnchoredAnchorSize)
   at Pisces.Domain.Logic.CandidateVariantFinder.ExtractInsertionFromOperation(Read alignment, String refChromosome, Int32 opStartIndexInRead, UInt32 operationLength, Int32 opStartIndexInReference, String chromosomeName)
   at Pisces.Domain.Logic.CandidateVariantFinder.ProcessCigarOps(Read alignment, String refChromosome, Int32 readStartPosition, String chromosomeName)
   at Pisces.Logic.SomaticVariantCaller.Execute()
   at Pisces.Processing.Logic.BaseGenomeProcessor.ProcessByBam(BamWorkRequest workRequest, String chrName)
   --- End of inner exception stack trace ---.
18/03/19 1:00 pm 1  Unloaded chromosome '19', all jobs complete.
18/03/19 1:02 pm 1  Exception reported:
System.IO.InvalidDataException: Alignment error: Found change in direction without encountering stitched direction
   at Pisces.Processing.Logic.BaseProcessor.Execute(Int32 maxThreads)
   at Pisces.Program.ProgramExecution()
   at CommandLine.Application.BaseApplication`1.Execute().

ERROR: Alignment error: Found change in direction without encountering stitched direction

Stack trace:
   at Pisces.Processing.Logic.BaseProcessor.Execute(Int32 maxThreads)
   at Pisces.Program.ProgramExecution()
   at CommandLine.Application.BaseApplication`1.Execute()
18/03/19 1:02 pm 1  ******************** Ending *********************

I don't see this with all the samples. Any help is appreciated!

Thank you,
Satwica

**Comment by saty89** [comment]
I should add that the vcf has been generated but the pipeline fails with the above error preventing the next steps to happen.

**Comment by tamsen** [comment]
Hi!

Thanks for your interest and support.  Did you set "-UseStitchedXD true" in Pisces? Would you mind please attaching PiscesOptions.used.json? That will let me see what settings Pisces is running with.

Thank you.

**Comment by saty89** [comment]
Hi Tamsen, yes I did. I attached one sample .json file here for reference. 
[PiscesOptions.used.json.gz](https://github.com/Illumina/Pisces/files/2986777/PiscesOptions.used.json.gz)

Thank you!

**Comment by tamsen** [comment]
hm. So your config looks fine. We might have to look a your bam to sort it out.  There must be a read in there that Pisces is having trouble understanding, something about the direction tag. The source of error might be with Gemini (as it wrote the read) but its hard to say.

I will ask around and see if anyone else has seen the errors you mention in issue #33 and #32.

If you are comfortable, would you like to send us the bam and see if we can figure it out? I can email you how to send it in.

**Comment by saty89** [comment]
Thanks Tamsen, it would be helpful to known if these issues have been seen before. Unfortunately, I am unable to share the bams.

**Comment by Varunachander** [comment]
Hi all, 
I encounter similar issue today as issue #33  while running Pisces using gemini 5.2.10.49. I tested first using a single bam and  I see errors in folders for GL000220, GL000199, GL000216  while running first step gemini. 

This is the error:
9/5/19 8:08 PM 1  Exception reported:
System.Exception: Application failed: 3 tasks failed.
  at GeminiMulti.GeminiMultiProcessor.Execute(ICliTaskManager cliTaskManager, Dictionary`2 chromRefIds, List`1 cmdLineList, ISamtoolsWrapper samtoolsWrapper)
  at GeminiMulti.Program.ProgramExecution()
  at CommandLine.Application.BaseApplication`1.Execute().
ERROR: Application failed: 3 tasks failed.
Stack trace:
  at GeminiMulti.GeminiMultiProcessor.Execute(ICliTaskManager cliTaskManager, Dictionary`2 chromRefIds, List`1 cmdLineList, ISamtoolsWrapper samtoolsWrapper)
  at GeminiMulti.Program.ProgramExecution()
  at CommandLine.Application.BaseApplication`1.Execute()
9/5/19 8:08 PM 1  ******************** Ending *********************

Any thoughts why this is happening?

Best,
Varuna

**Comment by fmazzarotto** [comment]
Hi all,
I am struggling with the same issue as #32. I am running the somatic workflow on exome sequencing data (GeminiMulti on the sorted and 'de-duped' bam (previously processed with GATK MarkDuplicates) -> re-sort, re-index output bam -> Pisces -> etc etc), but Pisces outputs this error on some of the samples, on different chromosomes:

`System.Exception: EOCPDX9-IDTp7UMI59-TTCGCCAT_S24_L004.PairRealigned.resorted.bam: Error processing chr 'chr12': Alignment error: Found change in direction without encountering stitched direction ---> Sys
tem.IO.InvalidDataException: Alignment error: Found change in direction without encountering stitched direction
   at Pisces.Domain.Logic.CandidateVariantFinder.GetSupportDirection(CandidateAllele candidate, Read bamAlignment, Int32 startIndexInRead)
   at Pisces.Domain.Logic.CandidateVariantFinder.Create(AlleleCategory type, String chromosome, Int32 coordinate, String reference, String alternate, Read alignment, Int32 startIndexInRead, Int32 wellAnchoredAnchorSize)
   at Pisces.Domain.Logic.CandidateVariantFinder.ExtractInsertionFromOperation(Read alignment, String refChromosome, Int32 opStartIndexInRead, UInt32 operationLength, Int32 opStartIndexInReference, String chromosomeName)
   at Pisces.Domain.Logic.CandidateVariantFinder.ProcessCigarOps(Read alignment, String refChromosome, Int32 readStartPosition, String chromosomeName)
   at Pisces.Logic.SomaticVariantCaller.Execute()
   at Pisces.Processing.Logic.BaseGenomeProcessor.ProcessByBam(BamWorkRequest workRequest, String chrName)
   --- End of inner exception stack trace ---.`

I am using the `--usestitchedxd true` option. I attach the [PiscesOptions.used.json.gz](https://github.com/Illumina/Pisces/files/5786144/PiscesOptions.used.json.gz) file for reference.

Thanks very much

**Comment by tamsen** [comment]
FYI, for people still getting this bug, please try:  https://github.com/tamsen/Pisces/releases/tag/v5.3.0.0

best
Tamsen
