### ISSUE TITLE
Gemini error - v5.2.10.49

### ISSUE THREAD

**Issue by saty89** [Illumina/Pisces#33]
Hi,

I encountered another issue in the new version with Gemini with the following error. (This is when the sample was re-run again. First time, it warned for Gemini_3, Gemini_5 and Gemini_9 processes)

21/03/19 10:57 pm 1  WARNING:   Processing failed for Gemini_5. See error log for details.
21/03/19 10:57 pm 1  Exception reported:
System.Exception: Application failed: 1 tasks failed.
   at GeminiMulti.GeminiMultiProcessor.Execute(ICliTaskManager cliTaskManager, Dictionary`2 chromRefIds, List`1 cmdLineList, ISamtoolsWrapper samtoolsWrapper)
   at GeminiMulti.Program.ProgramExecution()
   at CommandLine.Application.BaseApplication`1.Execute().

ERROR: Application failed: 1 tasks failed.

Stack trace:
   at GeminiMulti.GeminiMultiProcessor.Execute(ICliTaskManager cliTaskManager, Dictionary`2 chromRefIds, List`1 cmdLineList, ISamtoolsWrapper samtoolsWrapper)
   at GeminiMulti.Program.ProgramExecution()
   at CommandLine.Application.BaseApplication`1.Execute()
21/03/19 10:57 pm 1  ******************** Ending *********************

I attached the log for Gemini step for the tested sample. Any help appreciated! 

[Gemini_error.txt](https://github.com/Illumina/Pisces/files/2994569/Gemini_error.txt)

Thanks,
Satwica

**Comment by tamsen** [comment]
Thanks Satwica!

We'll keep you posted re issue 32 and 33.

**Comment by saty89** [comment]
Thanks Tamsen. Meanwhile, I will use the previous version as that was working well without any problems. Hopefully these new issues get resolved soon!

**Comment by gwennberry** [comment]
Hi @saty89 , unfortunately I can't really tell what's going wrong here based on this error (and I know you said the BAMs can't be shared)... but if you can hang tight for about another week we will have an updated version that will hopefully work for you!

**Comment by saty89** [comment]
Great, thanks!

**Comment by Varunachander** [comment]
Hi, 

I encountered an issue in the 5.2.10.49 version with Gemini with the following error. 
Gemini gave me following error for 3 folders: GL000220, GL000199, GL000216.

/5/19 8:08 PM 1  Exception reported:  
System.Exception: Application failed: 3 tasks failed.
   at GeminiMulti.GeminiMultiProcessor.Execute(ICliTaskManager cliTaskManager, Dictionary`2 chromRefIds, List`1 cmdLineList, ISamtoolsWrapper samtoolsWrapper)
   at GeminiMulti.Program.ProgramExecution()
   at CommandLine.Application.BaseApplication`1.Execute().

ERROR: Application failed: 3 tasks failed.

Stack trace:
   at GeminiMulti.GeminiMultiProcessor.Execute(ICliTaskManager cliTaskManager, Dictionary`2 chromRefIds, List`1 cmdLineList, ISamtoolsWrapper samtoolsWrapper)
   at GeminiMulti.Program.ProgramExecution()
   at CommandLine.Application.BaseApplication`1.Execute()
9/5/19 8:08 PM 1  ******************** Ending *********************

Any thoughts what might be going on?
Best, 
Varuna
