### ISSUE TITLE
Error Gemini 5.2.11

### ISSUE THREAD

**Issue by XavierMialhe** [Illumina/Pisces#38]
Hi, 
I have the following error :

**ERROR: Nullable object must have a value.**

**Stack trace:**
   _at System.Nullable`1.get_Value()
   at Gemini.BlockFactorySource.GetBlockProvider(Dictionary`2 refIdMapping, String chrom, IWriterSource writerSource, ConcurrentDictionary`2 progressTracker, ConcurrentDictionary`2 categoryLookup, ConcurrentDictionary`2 masterIndelLookup, ConcurrentDictionary`2 masterOutcomesLookup, ConcurrentDictionary`2 masterFinalIndels, ChrReference chrReference) in C:\Users\gberry\Downloads\Pisces5-release-Pisces_5_2_11_open\Pisces5-release-Pisces_5_2_11_open\src\lib\Gemini\BlockFactorySource.cs:line 59
   at Gemini.DataflowReadEvaluator.ProcessBam() in C:\Users\gberry\Downloads\Pisces5-release-Pisces_5_2_11_open\Pisces5-release-Pisces_5_2_11_open\src\lib\Gemini\DataflowReadEvaluator.cs:line 85
   at Gemini.GeminiWorkflow.Execute() in C:\Users\gberry\Downloads\Pisces5-release-Pisces_5_2_11_open\Pisces5-release-Pisces_5_2_11_open\src\lib\Gemini\GeminiWorkflow.cs:line 53
   at Gemini.Program.ProgramExecution() in C:\Users\gberry\Downloads\Pisces5-release-Pisces_5_2_11_open\Pisces5-release-Pisces_5_2_11_open\src\lib\Gemini\Program.cs:line 59
   at CommandLine.Application.BaseApplication`1.Execute() in C:\Users\gberry\Downloads\Pisces5-release-Pisces_5_2_11_open\Pisces5-release-Pisces_5_2_11_open\src\lib\CommandLine.Options\BaseApplication.cs:line 126_

with this command :

_dotnet /data/software/Gemini/Gemini.dll --bam ../../jeux_de_données/BAMSurgeon/mutationSNVandINDEL.sorted.addrg.bam --genome ../../jeux_de_données/BAMSurgeon/genome --samtools /data/software/samtools-1.7/samtools --outfolder Gemini_

**Comment by tamsen** [comment]
Hi!

Thanks for submitting the bug report. We are currently working on hardening Gemini, so we really appreciate hearing about any issues you find. This might be a bam parsing or loading issue. Are you sure your bam is well formatted? Do you typically have issues with BAMSurgeon bams vs regular bams, or is this issue a one-time-thing? Does your bam index OK with samtools?

Thanks,
Tamsen

**Comment by XavierMialhe** [comment]
Hi :)

I can assure you that my BAMs is well formatted. They work perfectly with Gemini 5.2.10 (except one BAM where i have the same error type than #33 )

I use the binaries of Gemini and Pisces, maybe I need to compile from source ?

When I'm looking the error, I see hard-coded path (_C:/Users/gberry_..) Is it normal ?

**Comment by tamsen** [comment]
Hi :)

Yes, its certainly both a bug and an unhandled exception. (I'll edit my first response to be more clear) I was just trying to dig more into what might have triggered it with my questions.

short answer: Yes, its a bit odd to see Gwenn's path there. We will check it out.

long answer: Its not unusual to see paths to original source in a stack trace. That being said, usually we release binaries created from the build server, not personal computers, because those are the exact binaries that went through test. In theory, if you recompile from source would that would change the paths in the stack trace but not the error itself. (caveat, over the years I have frequently seen I've been binaries behave differently depending on compilers, including creating different bugs down in the machine code,  :/ )

Anyway. Let us look into this. 

Thanks again,
-Tamsen

**Comment by Aargol** [comment]
Same error occurs. Any progress after 2 months?

**Comment by Aargol** [comment]
@XavierMialhe hi Xavier, i came across error "Could not resolve CoreCLR path" with v5.2.10 as well. 
my command:
dotnet geminimulti.dll -bam myr.bam -genome MyGenome -samtools /usr/local/bin/samtools --outFolder temp -numProcesses 8 -exePath Gemini.dll

Could you show me how you use gemini v5.2.10?

**Comment by janrehker** [comment]
> I can assure you that my BAMs is well formatted. They work perfectly with Gemini 5.2.10 (except one BAM where i have the same error type than #33 ) So I don't think it's a bam related issue but just software issue.
> 
> I use the binaries of Gemini and Pisces, maybe I need to compile from source ?
> 
> When I'm looking the error, I see hard-coded path (_C:/Users/gberry_..) Is it normal ?

Same here...
Is there still development going on regarding Gemini?

**Comment by tamsen** [comment]
Hi! 

Sorry for your frustration.  Go ahead and try this 5.3 version. It resolves some gemini stability issues.

https://github.com/tamsen/Pisces/releases/tag/v5.3.0.0

Make sure you see the readme for the command line changes between 5.2 and 5.3.  https://github.com/tamsen/Pisces

I haven't worked for illumina for ~2 years. I'm just fixing bugs pro bono when I can get a chance.  That's also why the 5.3 version is not an official illumina release. I hope it resolves your issues. If 5.3 does not solve your problem, please do leave a "issues" message on the  5.3 fork, and I'll get to it...when I can.

The 5.3 version is much more linux-developer-friendly, so if people in the community are interested in helping with debug or dev, drop me a line. It shouldn't be too hard to get into. Also that would be the best version to try if you want to recompile from source.   Re, future dev, there are a lot of things we could do to further improve results, but its tbd depending on time & community interest.

Thanks again for using Pisces, and I'm sorry for the frustration.

best
Tamsen

**Comment by janrehker** [comment]
Thanks for pointing us into the right direction!

Best regards,
Jan
